openapi: 3.0.0
info:
  title: Blogging API
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/blogs:
    get:
      summary: Get published blogs
      responses:
        '200':
          description: List of blogs
    post:
      summary: Create blog
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Blog created
  /api/blogs/{id}:
    get:
      summary: Get one published blog
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Blog object
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
